/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UxLabRouteImport } from './routes/ux-lab'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RuralRouteImport } from './routes/rural'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PsychologyRouteImport } from './routes/psychology'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as EyeTrackingRouteImport } from './routes/eye-tracking'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const UxLabRoute = UxLabRouteImport.update({
  id: '/ux-lab',
  path: '/ux-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralRoute = RuralRouteImport.update({
  id: '/rural',
  path: '/rural',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologyRoute = PsychologyRouteImport.update({
  id: '/psychology',
  path: '/psychology',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const EyeTrackingRoute = EyeTrackingRouteImport.update({
  id: '/eye-tracking',
  path: '/eye-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/case-studies': typeof CaseStudiesRoute
  '/eye-tracking': typeof EyeTrackingRoute
  '/funnel': typeof FunnelRoute
  '/psychology': typeof PsychologyRoute
  '/reports': typeof ReportsRoute
  '/rural': typeof RuralRoute
  '/tools': typeof ToolsRoute
  '/ux-lab': typeof UxLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/case-studies': typeof CaseStudiesRoute
  '/eye-tracking': typeof EyeTrackingRoute
  '/funnel': typeof FunnelRoute
  '/psychology': typeof PsychologyRoute
  '/reports': typeof ReportsRoute
  '/rural': typeof RuralRoute
  '/tools': typeof ToolsRoute
  '/ux-lab': typeof UxLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/case-studies': typeof CaseStudiesRoute
  '/eye-tracking': typeof EyeTrackingRoute
  '/funnel': typeof FunnelRoute
  '/psychology': typeof PsychologyRoute
  '/reports': typeof ReportsRoute
  '/rural': typeof RuralRoute
  '/tools': typeof ToolsRoute
  '/ux-lab': typeof UxLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/case-studies'
    | '/eye-tracking'
    | '/funnel'
    | '/psychology'
    | '/reports'
    | '/rural'
    | '/tools'
    | '/ux-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/case-studies'
    | '/eye-tracking'
    | '/funnel'
    | '/psychology'
    | '/reports'
    | '/rural'
    | '/tools'
    | '/ux-lab'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/case-studies'
    | '/eye-tracking'
    | '/funnel'
    | '/psychology'
    | '/reports'
    | '/rural'
    | '/tools'
    | '/ux-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  EyeTrackingRoute: typeof EyeTrackingRoute
  FunnelRoute: typeof FunnelRoute
  PsychologyRoute: typeof PsychologyRoute
  ReportsRoute: typeof ReportsRoute
  RuralRoute: typeof RuralRoute
  ToolsRoute: typeof ToolsRoute
  UxLabRoute: typeof UxLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ux-lab': {
      id: '/ux-lab'
      path: '/ux-lab'
      fullPath: '/ux-lab'
      preLoaderRoute: typeof UxLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural': {
      id: '/rural'
      path: '/rural'
      fullPath: '/rural'
      preLoaderRoute: typeof RuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychology': {
      id: '/psychology'
      path: '/psychology'
      fullPath: '/psychology'
      preLoaderRoute: typeof PsychologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eye-tracking': {
      id: '/eye-tracking'
      path: '/eye-tracking'
      fullPath: '/eye-tracking'
      preLoaderRoute: typeof EyeTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  EyeTrackingRoute: EyeTrackingRoute,
  FunnelRoute: FunnelRoute,
  PsychologyRoute: PsychologyRoute,
  ReportsRoute: ReportsRoute,
  RuralRoute: RuralRoute,
  ToolsRoute: ToolsRoute,
  UxLabRoute: UxLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
